# Generated by Django 4.1 on 2023-03-18 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anomally_Detect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title', max_length=255)),
                ('original', models.FileField(upload_to='anomaly_detect/original')),
                ('weekday_plot', models.ImageField(upload_to='anomaly_detect/weekday')),
                ('final', models.FileField(upload_to='anomaly_detect/final')),
                ('outliers', models.FileField(upload_to='anomaly_detect/outliers')),
                ('anomaly', models.FileField(upload_to='anomaly_detect/anomaly')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
