# Generated by Django 3.2.18 on 2023-03-22 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomally_detect',
            name='anomaly',
            field=models.FileField(blank=True, null=True, upload_to='anomaly_detect/anomaly'),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='final',
            field=models.FileField(blank=True, null=True, upload_to='anomaly_detect/final'),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='original',
            field=models.FileField(blank=True, null=True, upload_to='anomaly_detect/original'),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='outliers',
            field=models.FileField(blank=True, null=True, upload_to='anomaly_detect/outliers'),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='anomally_detect',
            name='weekday_plot',
            field=models.ImageField(blank=True, null=True, upload_to='anomaly_detect/weekday'),
        ),
    ]
